# Generated by Django 6.0.1 on 2026-02-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together={('email', 'company')},
        ),
    ]
